### ISSUE TITLE
Move out of range 

### ISSUE THREAD

**Issue by hemna** [kyleisah/Klipper-Adaptive-Meshing-Purging#202]
**Describe the issue**
A clear and concise description of what the bug is...
I just installed KAMP on my klipper install following the instructions on the README on github.
When I try and print the klipper adaptive purge tower, the line purge throws the Move out of range.

I didn't know where else to ask for help.

```09:11:47 
echo: KAMP Line Purge
09:11:47 
// Moving filament tip 0.0mms
09:11:47 
// KAMP purge is not using firmware retraction, it is recommended to configure it.
09:11:47 
// KAMP purge starting at 102.5, 64.334 and purging 30.0mm of filament, requested flow rate is 12.0mm/s3.
09:11:47 
!! Move out of range: 102.500 64.334 -1.343 [0.000]
09:11:47 
!! Move out of range: 102.500 64.334 -1.343 [0.000]
09:11:47 
!! Move out of range: 102.500 64.334 -1.343 [0.000]
```

**What slicer are you using?**
Cura 

**Troubleshooting**
No idea how to troubleshoot this.

**Screenshots**

**Klipper log file:**
Please add klipper log file here...

**Sliced Gcode**
Please add sliced gcode file you are using here...

**Additional context**

```
Moving filament tip 0.0mms
KAMP purge is using firmware retraction.
KAMP purge starting at 102.5, 64.334 and purging 30.0mm of filament, requested flow rate is 12.0mm/s3.
Move out of range: 102.500 64.334 -1.347 [0.000]
Move out of range: 102.500 64.334 -1.347 [0.000]
Move out of range: 102.500 64.334 -1.347 [0.000]
SDCARD_RESET_FILE cannot be run from the sdcard
SDCARD_RESET_FILE cannot be run from the sdcard
virtual_sdcard on_error
Traceback (most recent call last):
  File "/home/waboring/klipper/klippy/extras/virtual_sdcard.py", line 264, in work_handler
    self.gcode.run_script(line)
  File "/home/waboring/klipper/klippy/gcode.py", line 216, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/waboring/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/waboring/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/waboring/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/waboring/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/waboring/klipper/klippy/gcode.py", line 213, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/waboring/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/waboring/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/waboring/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/waboring/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/waboring/klipper/klippy/gcode.py", line 213, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/waboring/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/waboring/klipper/klippy/extras/gcode_move.py", line 143, in cmd_G1
    self.move_with_transform(self.last_position, self.speed)
  File "/home/waboring/klipper/klippy/extras/bed_mesh.py", line 215, in move
    self.toolhead.move(split_move, speed)
  File "/home/waboring/klipper/klippy/toolhead.py", line 422, in move
    self.kin.check_move(move)
  File "/home/waboring/klipper/klippy/kinematics/cartesian.py", line 113, in check_move
    self._check_endstops(move)
  File "/home/waboring/klipper/klippy/kinematics/cartesian.py", line 102, in _check_endstops
    raise move.move_error()
gcode.CommandError: Move out of range: 102.500 64.334 -1.347 [0.000]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/waboring/klipper/klippy/extras/virtual_sdcard.py", line 268, in work_handler
    self.gcode.run_script(self.on_error_gcode.render())
  File "/home/waboring/klipper/klippy/gcode.py", line 216, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/waboring/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/waboring/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/waboring/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/waboring/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/waboring/klipper/klippy/gcode.py", line 213, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/waboring/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/waboring/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/waboring/klipper/klippy/extras/virtual_sdcard.py", line 138, in cmd_SDCARD_RESET_FILE
    raise gcmd.error(
gcode.CommandError: SDCARD_RESET_FILE cannot be run from the sdcard
Exiting SD card print (position 618)
```

Here is my printer.cfg

```
# This file contains pin mappings for the stock 2020 Creality Ender 3
# with the 32-bit Creality 4.2.2 board. To use this config, during
# "make menuconfig" select the STM32F103 with a "28KiB bootloader" and
# serial (on USART1 PA10/PA9) communication.
# adapted for my printer ender3-4.2.2

# If you prefer a direct serial connection, in "make menuconfig"
# select "Enable extra low-level configuration options" and select
# serial (on USART3 PB11/PB10), which is broken out on the 10 pin IDC
# cable used for the LCD module as follows:
# 3: Tx, 4: Rx, 9: GND, 10: VCC

# Flash this firmware by copying "out/klipper.bin" to a SD card and
# turning on the printer with the card inserted. The firmware
# filename must end in ".bin" and must not match the last filename
# that was flashed.

# See docs/Config_Reference.md for a description of parameters.

[include fluidd.cfg]

#====================================================================
# INCLUDE MACROS
#====================================================================

[include macros.cfg]

#====================================================================
# VIRTUAL SD CARD
#====================================================================
[virtual_sdcard]
path: ~/printer_data/gcodes
on_error_gcode: CANCEL_PRINT


#====================================================================
# INCLUDE KAMP - Klipper Adaptive Meshing Purging
#====================================================================
[include KAMP_Settings.cfg]


#====================================================================
# EXCLUDE OBJECTS
#====================================================================

[exclude_object]


#====================================================================
# MCU
#====================================================================

[mcu]
serial: /dev/serial/by-id/pci--if00-port0
restart_method: command

#====================================================================
# Raspberry Pi Temperature Display for Mainsail
#====================================================================

[temperature_sensor raspberry_pi]
sensor_type: temperature_host
min_temp: 10
max_temp: 100

#====================================================================
# PRINTER
#====================================================================

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3500
max_accel_to_decel: 3500
max_z_velocity: 5
max_z_accel: 100
square_corner_velocity: 5

#====================================================================
# STEPPER X
#====================================================================

[stepper_x]
step_pin: PC2
dir_pin: PB9
enable_pin: !PC3
microsteps: 16
rotation_distance: 40
endstop_pin: ^PA5
position_endstop: 0
position_max: 235
position_min: -15
homing_speed: 50

#====================================================================
# STEPPER Y
#====================================================================

[stepper_y]
step_pin: PB8
dir_pin: PB7
enable_pin: !PC3
microsteps: 16
rotation_distance: 40
endstop_pin: ^PA6
position_endstop: 0
position_max: 230
position_min: -13
homing_speed: 50

#====================================================================
# STEPPER Z
#====================================================================

[stepper_z]
step_pin: PB6
dir_pin: !PB5
enable_pin: !PC3
microsteps: 16
rotation_distance: 8
endstop_pin: ^PA7
position_endstop: 0
position_max: 250

#====================================================================
# EXTRUDER
#====================================================================

[extruder]
max_extrude_only_distance: 100.0 # for rotation_distact calibration. Default is 50
step_pin: PB3
dir_pin: PB4
enable_pin: !PC3
microsteps: 16
gear_ratio: 42:12
rotation_distance: 26.359
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PA1
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC5
control: pid
pid_Kp: 23.561
pid_Ki: 1.208
pid_Kd: 114.859
min_temp: 0
max_temp: 300 # Set to 300 for Sprite Pro Extruder
min_extrude_temp: 170
max_extrude_cross_section: 5 # For KAMP purge
# It is recommended to calibrate your own pressure advance.
# See https://www.klipper3d.org/Pressure_Advance.html
#pressure_advance: .0465 # Overture PLA White
pressure_advance: .0369 # Polymaker PLA Pro Teal
pressure_advance_smooth_time: 0.04

#====================================================================
# CR TOUCH
#====================================================================

[bltouch]
sensor_pin: ^PB1
control_pin: PB0
#x_offset: -31.4
x_offset: -27.0
y_offset: -40.1
z_offset: 4
speed:35
samples:3
samples_result: median
samples_tolerance: 0.0075
samples_tolerance_retries: 10
probe_with_touch_mode: true
stow_on_each_sample: false

#====================================================================
# SAFE Z HOME
#====================================================================

[safe_z_home]
# Change coordinates to the center of your print bed
home_xy_position: 110, 110
speed: 75
# Move up 10mm
z_hop: 10
z_hop_speed: 5
move_to_previous: false

#====================================================================
# PAUSE RESUME
#====================================================================

[pause_resume]
recover_velocity: 25

#====================================================================
# BED
#====================================================================

[heater_bed]
heater_pin: PA2
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC4
control: pid
# tuned for stock hardware with 50 degree Celsius target
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 130

#====================================================================
# FANS
#====================================================================

[fan]
pin: PA0


#====================================================================
# SCREW ADJUSTMENT
#====================================================================

[bed_screws]
screw1: 25, 202 # Using rear left to take measurements as harder to reach
screw1_name: rear left screw
screw2: 195, 202
screw2_name: rear right screw
screw3: 195, 33
screw3_name: front right screw
screw4: 25, 33
screw4_name: front left screw

[screws_tilt_adjust]
screw1: 57, 229
screw1_name: rear left screw
screw2: 227, 229
screw2_name: rear right screw
screw3: 227, 70
screw3_name: front right screw
screw4: 57, 70
screw4_name: front left screw
horizontal_move_z: 10
speed: 50
screw_thread: CW-M4 # Use CW for Clowise and CCW for Counter Clockwise

#====================================================================
# BED MESH PARAMETERS
#====================================================================

[bed_mesh]
speed: 120
horizontal_move_z: 15
mesh_min: 15,15
mesh_max: 205,189
probe_count: 5,5
algorithm: bicubic
fade_start: 1
fade_end: 10
fade_target: 0

#====================================================================
# INPUT SHAPER
#====================================================================

# Klipper supports Input Shaping - a technique that can be used to
# reduce ringing (also known as echoing, ghosting or rippling) in
# prints. Ringing is a surface printing defect when, typically,
# elements like edges repeat themselves on a printed surface as a
# subtle 'echo':

# Every printer is different and the ringing frequency depends on
# the printer's mechanical properties. The ringing frequency can be
# measured by printing a simple test object and measuring the
# distance between the echoes. The ringing frequency is typically
# between 50 and 100 Hz.

# https://www.klipper3d.org/Resonance_Compensation.html

# Uncomment the following lines to enable input shaping. The
# shaper_freq_x and shaper_freq_y parameters should be set to the
# ringing frequency of the printer.

# MANUAL SETUP
# [input_shaper]
# shaper_freq_x: 54.85
# shaper_type_x: ei
# shaper_freq_y: 57.52
# shaper_type_y: mzv

[input_shaper]
shaper_freq_x: 68.8
shaper_type_x: mzv
shaper_freq_y: 44.4
shaper_type_y: mzv


[firmware_retraction]
retract_length: 5
#   The length of filament (in mm) to retract when G10 is activated,
#   and to unretract when G11 is activated (but see
#   unretract_extra_length below). The default is 0 mm.
#retract_speed: 20
#   The speed of retraction, in mm/s. The default is 20 mm/s.
#unretract_extra_length: 0
#   The length (in mm) of *additional* filament to add when
#   unretracting.
#unretract_speed: 10
#   The speed of unretraction, in mm/s. The default is 10 mm/s.



#====================================================================
# ARC SUPPORT
#====================================================================

[gcode_arcs]
resolution = 1.0

[gcode_macro G29]
gcode:
 G28
 BED_MESH_CALIBRATE
 G1 X0 Y0 Z5 F4000

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	  -2.052500, -2.082500, -2.030000, -2.060000, -2.260000
#*# 	  -2.040000, -2.092500, -2.085000, -2.147500, -2.367500
#*# 	  -2.097500, -2.132500, -2.102500, -2.157500, -2.355000
#*# 	  -2.097500, -2.125000, -2.097500, -2.147500, -2.332500
#*# 	  -2.065000, -2.100000, -2.067500, -2.105000, -2.310000
#*# x_count = 5
#*# y_count = 5
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = lagrange
#*# tension = 0.2
#*# min_x = 15.0
#*# max_x = 205.0
#*# min_y = 15.0
#*# max_y = 189.0
```

This is the first part of the gcode file

```
;FLAVOR:Marlin
;TIME:4747
;Filament used: 8.18872m
;Layer height: 0.3
;MINX:73.515
;MINY:73.534
;MINZ:0.2
;MAXX:161.485
;MAXY:161.466
;MAXZ:50
;KLIPPERSETTINGSPROCESSED
SET_RETRACTION RETRACT_LENGTH=5 RETRACT_SPEED=45 UNRETRACT_SPEED=45 ;KlipperSettingsPlugin


; Pre-Processed for Cancel-Object support by preprocess_cancellation v0.2.0
; 1 known objects
EXCLUDE_OBJECT_DEFINE NAME=square_tower_stl CENTER=117.508,116.967 POLYGON=[[74.315,74.334],[74.315,160.666],[160.685,160.666],[160.685,74.334]]

;Generated with Cura_SteamEngine 5.4.0
M140 S50
M105
M190 S50
M104 S200
M105
M109 S200
M82 ;absolute extrusion mode
START_PRINT
G92 E0
G92 E0
G10
;LAYER_COUNT:167
;LAYER:0
M107
G0 F6000 X78.497 Y77.904 Z0.2
;TYPE:SKIRT
G11
G1 F1200 X79.476 Y77.069 E0.0428
G1 X80.138 Y76.568 E0.07041
G1 X80.673 Y76.185 E0.09229
G1 X81.466 Y75.681 E0.12354
G1 X82.373 Y75.211 E0.15752
G1 X83.353 Y74.762 E0.19337
G1 X84.19 Y74.422 E0.22342
G1 X85.407 Y74.062 E0.26563
G1 X86.17 Y73.884 E0.29169
G1 X86.746 Y73.764 E0.31126
G1 X87.751 Y73.611 E0.34507
G1 X88.693 Y73.55 E0.37647
G1 X89.495 Y73.534 E0.40315
G1 X90.163 Y73.539 E0.42537
G1 X91.135 Y73.599 E0.45776
G1 X91.997 Y73.727 E0.48674
G1 X93.197 Y73.964 E0.52743
G1 X94.502 Y74.261 E0.57194
G1 X97 Y74.793 E0.65689
...
...
```

**Comment by kyleisah** [comment]
What do you have the purge_height variable set to?

**Comment by hemna** [comment]
variable_purge_height: 0.8

Here is my KAMP_Settings.cfg

```
# Below you can include specific configuration files depending on what you want KAMP to do:

[include ./KAMP/Adaptive_Meshing.cfg]       # Include to enable adaptive meshing configuration.
[include ./KAMP/Line_Purge.cfg]             # Include to enable adaptive line purging configuration.
# [include ./KAMP/Voron_Purge.cfg]            # Include to enable adaptive Voron logo purging configuration.
# [include ./KAMP/Smart_Park.cfg]             # Include to enable the Smart Park function, which parks the printhead near the print area for final heating.

[gcode_macro _KAMP_Settings]
description: This macro contains all adjustable settings for KAMP 

# The following variables are settings for KAMP as a whole.
variable_verbose_enable: True               # Set to True to enable KAMP information output when running. This is useful for debugging.

# The following variables are for adjusting adaptive mesh settings for KAMP.
variable_mesh_margin: 20                     # Expands the mesh size in millimeters if desired. Leave at 0 to disable.
variable_fuzz_amount: 5                     # Slightly randomizes mesh points to spread out wear from nozzle-based probes. Leave at 0 to disable.

# The following variables are for those with a dockable probe like Klicky, Euclid, etc.                 # ----------------  Attach Macro | Detach Macro
variable_probe_dock_enable: False           # Set to True to enable the usage of a dockable probe.      # ---------------------------------------------
variable_attach_macro: 'Attach_Probe'       # The macro that is used to attach the probe.               # Klicky Probe:   'Attach_Probe' | 'Dock_Probe'
variable_detach_macro: 'Dock_Probe'         # The macro that is used to store the probe.                # Euclid Probe:   'Deploy_Probe' | 'Stow_Probe'
                                                                                                        # Legacy Gcode:   'M401'         | 'M402'

# The following variables are for adjusting adaptive purge settings for KAMP.
variable_purge_height: 0.8                  # Z position of nozzle during purge, default is 0.8.
variable_tip_distance: 0                    # Distance between tip of filament and nozzle before purge. Should be similar to PRINT_END final retract amount.
variable_purge_margin: 10                   # Distance the purge will be in front of the print area, default is 10.
variable_purge_amount: 30                   # Amount of filament to be purged prior to printing.
variable_flow_rate: 12                      # Flow rate of purge in mm3/s. Default is 12.

# The following variables are for adjusting the Smart Park feature for KAMP, which will park the printhead near the print area at a specified height.
variable_smart_park_height: 10              # Z position for Smart Park, default is 10.

gcode: # Gcode section left intentionally blank. Do not disturb.

    {action_respond_info(" Running the KAMP_Settings macro does nothing, it is only used for storing KAMP settings. ")}
```

**Comment by kyleisah** [comment]
Well, for some reason when trying to purge, it's trying to move to a negative Z position. I think this has something to do with your bed mesh settings and not KAMP. 

Something you can try is adding `zero_reference_position` to your [bed_mesh] config block. The position should be the wherever your printer homes to if it homes with a probe, like the center point of the bed. 

More info here:

https://www.klipper3d.org/Bed_Mesh.html#configuring-the-zero-reference-position

**Comment by JurajMik** [comment]
Here is sanity check for bed_mesh_calibrate.cfg
